# permissions for end users to view custommetrics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custommetric-viewer-role
rules:
- apiGroups:
  - cm.example.com
  resources:
  - custommetrics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cm.example.com
  resources:
  - custommetrics/status
  verbs:
  - get
