apiVersion: cmoperator.io/v1alpha1
kind: CustomMetric
metadata:
  name: cm
spec:
  project: nmiu-play
  cluster: foo2
  location: us-central1-a
  metrics:
    - cilium_.*
    - container_network_transmit_packets_total
    - container_network_receive_packets_total
