apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: custommetrics.promoperator.k8s.io
spec:
  group: promoperator.k8s.io
  version: v1alpha1
  names:
    kind: CustomMetric
    plural: custommetrics
  scope: Namespaced
  subresources:
    status: {}
