apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: custommetrics.promoperator.k8s.io
spec:
  group: promoperator.k8s.io
  version: v1alpha1
  names:
    kind: CustomMetric
    listKind: CustomMetricList
    plural: custommetrics
    singular: custommetric
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
          - projectName
          - clusterName
          - location
          - sidecarTag
          - sidecarArgs
          properties:
            projectName:
              type: string
            clusterName:
              type: string
            location:
              type: string
            sidecarTag:
              type: string
            sidecarArgs:
              type: array
              items:
                type: string
