apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: custommetrics.cmoperator.k8s.io
  annotations:
    "api-approved.kubernetes.io": "https://github.com/kubernetes/kubernetes/pull/78458"
spec:
  group: cmoperator.k8s.io
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                project:
                  type: string
                cluster:
                  type: string
                location:
                  type: string
                metrics:
                  type: array
                  items:
                    type: string
              required:
                - project
                - cluster
                - location
                - metrics
            status:
              type: object
              properties:
                availableReplicas:
                  type: integer
      subresources:
        # status enables the status subresource.
        status: {}
  names:
    kind: CustomMetric
    listKind: CustomMetricList
    plural: custommetrics
    singular: custommetric
    shortNames:
      - cm
  scope: Namespaced